services:
  db:
    container_name: sense7-mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - 3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  wordpress:
    container_name: sense7-wp
    depends_on:
      - db
    image: wordpress:php8.4-apache
    restart: on-failure
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

  phpmyadmin:
    container_name: sense7-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    ports:
      - 80
