services:
  db:
    container_name: sense7-mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - 3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  redis:
    container_name: sense7-redis
    image: redis:alpine
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - 6379
    volumes:
      - ./.docker/redis:/data

  wordpress:
    container_name: sense7-wp
    depends_on:
      - db
    # image: wordpress:php8.4-apache
    build:
      context: .
      dockerfile: ./.docker/wordpress/Dockerfile
    restart: on-failure
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./.docker/wordpress.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./xdebug-profiles:/tmp/xdebug-profiles

  wp-cli:
    container_name: sense7-wp-cli
    image: wordpress:cli-php8.4
    depends_on:
      - wordpress
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./.docker/wp-cli.ini:/usr/local/etc/php/conf.d/php-custom.ini
    working_dir: /var/www/html

  phpmyadmin:
    container_name: sense7-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    ports:
      - 80

  webgrind:
    container_name: sense7-webgrind
    image: jokkedk/webgrind
    platform: linux/amd64
    depends_on:
      - wordpress
    ports:
      - 80
    volumes:
      - ./xdebug-profiles:/tmp

  mailhog:
    container_name: sense7-mailhog
    image: mailhog/mailhog
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - 1025
      - 8025
